gdb: add fix for gdb 7.12 build on noMMU platforms
This adds a patch to gdb 7.12, which fixes the build on noMMU
platforms. It is not needed for older versions of gdb, since it's
related to the switch of gdb to C++ in the 7.12 release.

Fixes:

../nat/linux-ptrace.c: In function 'int linux_fork_to_function(gdb_byte*, int (*)(void*))':
../nat/linux-ptrace.c:273:29: error: invalid conversion from 'void*' to 'gdb_byte* {aka unsigned char*}' [-fpermissive]
       child_stack = xmalloc (STACK_SIZE * 4);

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>